/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateEventDto } from '../models';
// @ts-ignore
import type { EntityConnectionDto } from '../models';
// @ts-ignore
import type { EventDto } from '../models';
// @ts-ignore
import type { GetEventsDto } from '../models';
// @ts-ignore
import type { MutateEventEntityConnectionDto } from '../models';
// @ts-ignore
import type { UpdateEventDto } from '../models';
// @ts-ignore
import type { UserEntityConnectionDto } from '../models';
/**
 * EventApi - axios parameter creator
 */
export const EventApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addConnection: async (eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('addConnection', 'eventId', eventId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addConnection', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('addConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'mutateEventEntityConnectionDto' is not null or undefined
            assertParamExists('addConnection', 'mutateEventEntityConnectionDto', mutateEventEntityConnectionDto)
            const localVarPath = `/event/{eventId}/connection/{userId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mutateEventEntityConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create an event. Owner will be the user creating the event or the group associated with the event (if set)
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (xProximaNexusRequesterUserId: string, createEventDto: CreateEventDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('create', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'createEventDto' is not null or undefined
            assertParamExists('create', 'createEventDto', createEventDto)
            const localVarPath = `/event`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, 401 may be returned if the user cannot view the event, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (eventId: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('get', 'eventId', eventId)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch: async (getEventsDto: GetEventsDto, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getEventsDto' is not null or undefined
            assertParamExists('getBatch', 'getEventsDto', getEventsDto)
            const localVarPath = `/event/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getEventsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get connections of an event
         * @param {string} eventId 
         * @param {Array<EventControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the event. If set, 401 may be returned if the user cannot view the event connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections: async (eventId: string, type?: Array<EventControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getConnections', 'eventId', eventId)
            const localVarPath = `/event/{eventId}/connections`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (type) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the event
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (eventId: string, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('remove', 'eventId', eventId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('remove', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove an attendee from an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeConnection: async (eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('removeConnection', 'eventId', eventId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('removeConnection', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('removeConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'mutateEventEntityConnectionDto' is not null or undefined
            assertParamExists('removeConnection', 'mutateEventEntityConnectionDto', mutateEventEntityConnectionDto)
            const localVarPath = `/event/{eventId}/connection/{userId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mutateEventEntityConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/event`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (displayName !== undefined) {
                localVarQueryParameter['displayName'] = displayName;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (minLatitude !== undefined) {
                localVarQueryParameter['minLatitude'] = minLatitude;
            }

            if (maxLatitude !== undefined) {
                localVarQueryParameter['maxLatitude'] = maxLatitude;
            }

            if (minLongitude !== undefined) {
                localVarQueryParameter['minLongitude'] = minLongitude;
            }

            if (maxLongitude !== undefined) {
                localVarQueryParameter['maxLongitude'] = maxLongitude;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the event
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (eventId: string, xProximaNexusRequesterUserId: string, updateEventDto: UpdateEventDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('update', 'eventId', eventId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('update', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'updateEventDto' is not null or undefined
            assertParamExists('update', 'updateEventDto', updateEventDto)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventApi - functional programming interface
 */
export const EventApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityConnectionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.addConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create an event. Owner will be the user creating the event or the group associated with the event (if set)
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(xProximaNexusRequesterUserId: string, createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(xProximaNexusRequesterUserId, createEventDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, 401 may be returned if the user cannot view the event, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(eventId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(eventId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatch(getEventsDto: GetEventsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatch(getEventsDto, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.getBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get connections of an event
         * @param {string} eventId 
         * @param {Array<EventControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the event. If set, 401 may be returned if the user cannot view the event connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConnections(eventId: string, type?: Array<EventControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConnections(eventId, type, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.getConnections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the event
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(eventId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove an attendee from an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.removeConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the event
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(eventId: string, xProximaNexusRequesterUserId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(eventId, xProximaNexusRequesterUserId, updateEventDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventApi - factory interface
 */
export const EventApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventApiFp(configuration)
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto> {
            return localVarFp.addConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create an event. Owner will be the user creating the event or the group associated with the event (if set)
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(xProximaNexusRequesterUserId: string, createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.create(xProximaNexusRequesterUserId, createEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, 401 may be returned if the user cannot view the event, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(eventId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<EventDto> {
            return localVarFp.get(eventId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch(getEventsDto: GetEventsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>> {
            return localVarFp.getBatch(getEventsDto, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get connections of an event
         * @param {string} eventId 
         * @param {Array<EventControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the event. If set, 401 may be returned if the user cannot view the event connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections(eventId: string, type?: Array<EventControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>> {
            return localVarFp.getConnections(eventId, type, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the event
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(eventId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove an attendee from an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
         * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>> {
            return localVarFp.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the event
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(eventId: string, xProximaNexusRequesterUserId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.update(eventId, xProximaNexusRequesterUserId, updateEventDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventApi - interface
 */
export interface EventApiInterface {
    /**
     * 
     * @summary Add an attendee to an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
     * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto>;

    /**
     * 
     * @summary Create an event. Owner will be the user creating the event or the group associated with the event (if set)
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the event
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(xProximaNexusRequesterUserId: string, createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @summary Get an event by ID
     * @param {string} eventId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, 401 may be returned if the user cannot view the event, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(eventId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<EventDto>;

    /**
     * 
     * @summary Get a batch of events by IDs
     * @param {GetEventsDto} getEventsDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBatch(getEventsDto: GetEventsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>>;

    /**
     * 
     * @summary Get connections of an event
     * @param {string} eventId 
     * @param {Array<EventControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the event. If set, 401 may be returned if the user cannot view the event connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConnections(eventId: string, type?: Array<EventControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>>;

    /**
     * 
     * @summary Delete an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the event
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Remove an attendee from an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
     * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Search events
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>>;

    /**
     * 
     * @summary Update an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the event
     * @param {UpdateEventDto} updateEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(eventId: string, xProximaNexusRequesterUserId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * EventApi - object-oriented interface
 */
export class EventApi extends BaseAPI implements EventApiInterface {
    /**
     * 
     * @summary Add an attendee to an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
     * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).addConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create an event. Owner will be the user creating the event or the group associated with the event (if set)
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the event
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(xProximaNexusRequesterUserId: string, createEventDto: CreateEventDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).create(xProximaNexusRequesterUserId, createEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an event by ID
     * @param {string} eventId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, 401 may be returned if the user cannot view the event, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public get(eventId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).get(eventId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a batch of events by IDs
     * @param {GetEventsDto} getEventsDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBatch(getEventsDto: GetEventsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).getBatch(getEventsDto, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get connections of an event
     * @param {string} eventId 
     * @param {Array<EventControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the event. If set, 401 may be returned if the user cannot view the event connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getConnections(eventId: string, type?: Array<EventControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).getConnections(eventId, type, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the event
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).remove(eventId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove an attendee from an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing an attendee from the event
     * @param {MutateEventEntityConnectionDto} mutateEventEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeConnection(eventId: string, userId: string, xProximaNexusRequesterUserId: string, mutateEventEntityConnectionDto: MutateEventEntityConnectionDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).removeConnection(eventId, userId, xProximaNexusRequesterUserId, mutateEventEntityConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search events
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for events. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the event
     * @param {UpdateEventDto} updateEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(eventId: string, xProximaNexusRequesterUserId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).update(eventId, xProximaNexusRequesterUserId, updateEventDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export enum EventControllerGetConnectionsTypeEnum {
    attendee = 'attendee',
    admin = 'admin',
    owner = 'owner'
}
