/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateEventDto } from '../models';
// @ts-ignore
import type { EntityConnectionDto } from '../models';
// @ts-ignore
import type { EventDto } from '../models';
// @ts-ignore
import type { GetEventsDto } from '../models';
// @ts-ignore
import type { UpdateEventDto } from '../models';
// @ts-ignore
import type { UserEntityConnectionDto } from '../models';
/**
 * EventApi - axios parameter creator
 */
export const EventApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAttendee: async (eventId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('addAttendee', 'eventId', eventId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addAttendee', 'userId', userId)
            const localVarPath = `/event/{eventId}/attendees/{userId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create an event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createEventDto: CreateEventDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createEventDto' is not null or undefined
            assertParamExists('create', 'createEventDto', createEventDto)
            const localVarPath = `/event`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('findOne', 'eventId', eventId)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get attendees of an event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendees: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getAttendees', 'eventId', eventId)
            const localVarPath = `/event/{eventId}/attendees`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch: async (getEventsDto: GetEventsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getEventsDto' is not null or undefined
            assertParamExists('getBatch', 'getEventsDto', getEventsDto)
            const localVarPath = `/event/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getEventsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId Requester user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (eventId: string, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('remove', 'eventId', eventId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('remove', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/event`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (displayName !== undefined) {
                localVarQueryParameter['displayName'] = displayName;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (minLatitude !== undefined) {
                localVarQueryParameter['minLatitude'] = minLatitude;
            }

            if (maxLatitude !== undefined) {
                localVarQueryParameter['maxLatitude'] = maxLatitude;
            }

            if (minLongitude !== undefined) {
                localVarQueryParameter['minLongitude'] = minLongitude;
            }

            if (maxLongitude !== undefined) {
                localVarQueryParameter['maxLongitude'] = maxLongitude;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (eventId: string, updateEventDto: UpdateEventDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('update', 'eventId', eventId)
            // verify required parameter 'updateEventDto' is not null or undefined
            assertParamExists('update', 'updateEventDto', updateEventDto)
            const localVarPath = `/event/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventApi - functional programming interface
 */
export const EventApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAttendee(eventId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityConnectionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAttendee(eventId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.addAttendee']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create an event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createEventDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findOne(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findOne(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.findOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get attendees of an event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendees(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendees(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.getAttendees']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatch(getEventsDto: GetEventsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatch(getEventsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.getBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId Requester user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(eventId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(eventId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(eventId, updateEventDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventApi - factory interface
 */
export const EventApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventApiFp(configuration)
    return {
        /**
         * 
         * @summary Add an attendee to an event
         * @param {string} eventId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAttendee(eventId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto> {
            return localVarFp.addAttendee(eventId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create an event
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.create(createEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an event by ID
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventDto> {
            return localVarFp.findOne(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get attendees of an event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendees(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>> {
            return localVarFp.getAttendees(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a batch of events by IDs
         * @param {GetEventsDto} getEventsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch(getEventsDto: GetEventsDto, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>> {
            return localVarFp.getBatch(getEventsDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an event
         * @param {string} eventId 
         * @param {string} xProximaNexusRequesterUserId Requester user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(eventId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search events
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>> {
            return localVarFp.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an event
         * @param {string} eventId 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(eventId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.update(eventId, updateEventDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventApi - interface
 */
export interface EventApiInterface {
    /**
     * 
     * @summary Add an attendee to an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addAttendee(eventId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto>;

    /**
     * 
     * @summary Create an event
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(createEventDto: CreateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @summary Get an event by ID
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findOne(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventDto>;

    /**
     * 
     * @summary Get attendees of an event
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAttendees(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>>;

    /**
     * 
     * @summary Get a batch of events by IDs
     * @param {GetEventsDto} getEventsDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBatch(getEventsDto: GetEventsDto, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>>;

    /**
     * 
     * @summary Delete an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId Requester user ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Search events
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>>;

    /**
     * 
     * @summary Update an event
     * @param {string} eventId 
     * @param {UpdateEventDto} updateEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(eventId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * EventApi - object-oriented interface
 */
export class EventApi extends BaseAPI implements EventApiInterface {
    /**
     * 
     * @summary Add an attendee to an event
     * @param {string} eventId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addAttendee(eventId: string, userId: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).addAttendee(eventId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create an event
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(createEventDto: CreateEventDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).create(createEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an event by ID
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public findOne(eventId: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).findOne(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get attendees of an event
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAttendees(eventId: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).getAttendees(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a batch of events by IDs
     * @param {GetEventsDto} getEventsDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBatch(getEventsDto: GetEventsDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).getBatch(getEventsDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an event
     * @param {string} eventId 
     * @param {string} xProximaNexusRequesterUserId Requester user ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(eventId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).remove(eventId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search events
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an event
     * @param {string} eventId 
     * @param {UpdateEventDto} updateEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(eventId: string, updateEventDto: UpdateEventDto, options?: RawAxiosRequestConfig) {
        return EventApiFp(this.configuration).update(eventId, updateEventDto, options).then((request) => request(this.axios, this.basePath));
    }
}

