/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateEventSeriesDto } from '../models';
// @ts-ignore
import type { EventDto } from '../models';
// @ts-ignore
import type { EventSeriesDto } from '../models';
// @ts-ignore
import type { UpdateEventSeriesDto } from '../models';
/**
 * EventSeriesApi - axios parameter creator
 */
export const EventSeriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a series definition and pre-generates all event instances based on the RRULE. The creating user (or associated group) becomes the OWNER.
         * @summary Create an event series
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the series
         * @param {CreateEventSeriesDto} createEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (xProximaNexusRequesterUserId: string, createEventSeriesDto: CreateEventSeriesDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('create', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'createEventSeriesDto' is not null or undefined
            assertParamExists('create', 'createEventSeriesDto', createEventSeriesDto)
            const localVarPath = `/event-series`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEventSeriesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an event series by ID
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (seriesId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seriesId' is not null or undefined
            assertParamExists('get', 'seriesId', seriesId)
            const localVarPath = `/event-series/{seriesId}`
                .replace(`{${"seriesId"}}`, encodeURIComponent(String(seriesId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all event instances (past and upcoming) belonging to this series, ordered by start time.
         * @summary List all event instances in a series
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstances: async (seriesId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seriesId' is not null or undefined
            assertParamExists('getInstances', 'seriesId', seriesId)
            const localVarPath = `/event-series/{seriesId}/events`
                .replace(`{${"seriesId"}}`, encodeURIComponent(String(seriesId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the series and all upcoming event instances. Past instances (already started) are preserved.
         * @summary Delete an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the series
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (seriesId: string, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seriesId' is not null or undefined
            assertParamExists('remove', 'seriesId', seriesId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('remove', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/event-series/{seriesId}`
                .replace(`{${"seriesId"}}`, encodeURIComponent(String(seriesId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the series definition and propagates metadata changes to all upcoming event instances. Fields that were individually overridden on a specific instance will not be overwritten.
         * @summary Update an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the series
         * @param {UpdateEventSeriesDto} updateEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (seriesId: string, xProximaNexusRequesterUserId: string, updateEventSeriesDto: UpdateEventSeriesDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'seriesId' is not null or undefined
            assertParamExists('update', 'seriesId', seriesId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('update', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'updateEventSeriesDto' is not null or undefined
            assertParamExists('update', 'updateEventSeriesDto', updateEventSeriesDto)
            const localVarPath = `/event-series/{seriesId}`
                .replace(`{${"seriesId"}}`, encodeURIComponent(String(seriesId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateEventSeriesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventSeriesApi - functional programming interface
 */
export const EventSeriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventSeriesApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a series definition and pre-generates all event instances based on the RRULE. The creating user (or associated group) becomes the OWNER.
         * @summary Create an event series
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the series
         * @param {CreateEventSeriesDto} createEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(xProximaNexusRequesterUserId: string, createEventSeriesDto: CreateEventSeriesDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(xProximaNexusRequesterUserId, createEventSeriesDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventSeriesApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an event series by ID
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(seriesId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventSeriesDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(seriesId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventSeriesApi.get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all event instances (past and upcoming) belonging to this series, ordered by start time.
         * @summary List all event instances in a series
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInstances(seriesId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInstances(seriesId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventSeriesApi.getInstances']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the series and all upcoming event instances. Past instances (already started) are preserved.
         * @summary Delete an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the series
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(seriesId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(seriesId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventSeriesApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the series definition and propagates metadata changes to all upcoming event instances. Fields that were individually overridden on a specific instance will not be overwritten.
         * @summary Update an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the series
         * @param {UpdateEventSeriesDto} updateEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(seriesId: string, xProximaNexusRequesterUserId: string, updateEventSeriesDto: UpdateEventSeriesDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(seriesId, xProximaNexusRequesterUserId, updateEventSeriesDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventSeriesApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventSeriesApi - factory interface
 */
export const EventSeriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventSeriesApiFp(configuration)
    return {
        /**
         * Creates a series definition and pre-generates all event instances based on the RRULE. The creating user (or associated group) becomes the OWNER.
         * @summary Create an event series
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the series
         * @param {CreateEventSeriesDto} createEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(xProximaNexusRequesterUserId: string, createEventSeriesDto: CreateEventSeriesDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.create(xProximaNexusRequesterUserId, createEventSeriesDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an event series by ID
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(seriesId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventSeriesDto> {
            return localVarFp.get(seriesId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all event instances (past and upcoming) belonging to this series, ordered by start time.
         * @summary List all event instances in a series
         * @param {string} seriesId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstances(seriesId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>> {
            return localVarFp.getInstances(seriesId, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the series and all upcoming event instances. Past instances (already started) are preserved.
         * @summary Delete an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the series
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(seriesId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(seriesId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the series definition and propagates metadata changes to all upcoming event instances. Fields that were individually overridden on a specific instance will not be overwritten.
         * @summary Update an event series
         * @param {string} seriesId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the series
         * @param {UpdateEventSeriesDto} updateEventSeriesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(seriesId: string, xProximaNexusRequesterUserId: string, updateEventSeriesDto: UpdateEventSeriesDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.update(seriesId, xProximaNexusRequesterUserId, updateEventSeriesDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventSeriesApi - interface
 */
export interface EventSeriesApiInterface {
    /**
     * Creates a series definition and pre-generates all event instances based on the RRULE. The creating user (or associated group) becomes the OWNER.
     * @summary Create an event series
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the series
     * @param {CreateEventSeriesDto} createEventSeriesDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(xProximaNexusRequesterUserId: string, createEventSeriesDto: CreateEventSeriesDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @summary Get an event series by ID
     * @param {string} seriesId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(seriesId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventSeriesDto>;

    /**
     * Returns all event instances (past and upcoming) belonging to this series, ordered by start time.
     * @summary List all event instances in a series
     * @param {string} seriesId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstances(seriesId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventDto>>;

    /**
     * Deletes the series and all upcoming event instances. Past instances (already started) are preserved.
     * @summary Delete an event series
     * @param {string} seriesId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the series
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(seriesId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Updates the series definition and propagates metadata changes to all upcoming event instances. Fields that were individually overridden on a specific instance will not be overwritten.
     * @summary Update an event series
     * @param {string} seriesId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the series
     * @param {UpdateEventSeriesDto} updateEventSeriesDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(seriesId: string, xProximaNexusRequesterUserId: string, updateEventSeriesDto: UpdateEventSeriesDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * EventSeriesApi - object-oriented interface
 */
export class EventSeriesApi extends BaseAPI implements EventSeriesApiInterface {
    /**
     * Creates a series definition and pre-generates all event instances based on the RRULE. The creating user (or associated group) becomes the OWNER.
     * @summary Create an event series
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the series
     * @param {CreateEventSeriesDto} createEventSeriesDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(xProximaNexusRequesterUserId: string, createEventSeriesDto: CreateEventSeriesDto, options?: RawAxiosRequestConfig) {
        return EventSeriesApiFp(this.configuration).create(xProximaNexusRequesterUserId, createEventSeriesDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an event series by ID
     * @param {string} seriesId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public get(seriesId: string, options?: RawAxiosRequestConfig) {
        return EventSeriesApiFp(this.configuration).get(seriesId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all event instances (past and upcoming) belonging to this series, ordered by start time.
     * @summary List all event instances in a series
     * @param {string} seriesId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getInstances(seriesId: string, options?: RawAxiosRequestConfig) {
        return EventSeriesApiFp(this.configuration).getInstances(seriesId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the series and all upcoming event instances. Past instances (already started) are preserved.
     * @summary Delete an event series
     * @param {string} seriesId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the series
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(seriesId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return EventSeriesApiFp(this.configuration).remove(seriesId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the series definition and propagates metadata changes to all upcoming event instances. Fields that were individually overridden on a specific instance will not be overwritten.
     * @summary Update an event series
     * @param {string} seriesId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the series
     * @param {UpdateEventSeriesDto} updateEventSeriesDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(seriesId: string, xProximaNexusRequesterUserId: string, updateEventSeriesDto: UpdateEventSeriesDto, options?: RawAxiosRequestConfig) {
        return EventSeriesApiFp(this.configuration).update(seriesId, xProximaNexusRequesterUserId, updateEventSeriesDto, options).then((request) => request(this.axios, this.basePath));
    }
}

