/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateGroupDto } from '../models';
// @ts-ignore
import type { EntityConnectionDto } from '../models';
// @ts-ignore
import type { EventEntityConnectionDto } from '../models';
// @ts-ignore
import type { GetGroupsDto } from '../models';
// @ts-ignore
import type { GroupDto } from '../models';
// @ts-ignore
import type { MutateGroupEntityConnectionDto } from '../models';
// @ts-ignore
import type { UpdateGroupDto } from '../models';
// @ts-ignore
import type { UserEntityConnectionDto } from '../models';
/**
 * GroupApi - axios parameter creator
 */
export const GroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add or update a connection to a group (member, admin, or owner)
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user adding a connection to the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addConnection: async (groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('addConnection', 'groupId', groupId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addConnection', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('addConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'mutateGroupEntityConnectionDto' is not null or undefined
            assertParamExists('addConnection', 'mutateGroupEntityConnectionDto', mutateGroupEntityConnectionDto)
            const localVarPath = `/group/{groupId}/connection/{userId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mutateGroupEntityConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a group
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the group
         * @param {CreateGroupDto} createGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (xProximaNexusRequesterUserId: string, createGroupDto: CreateGroupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('create', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'createGroupDto' is not null or undefined
            assertParamExists('create', 'createGroupDto', createGroupDto)
            const localVarPath = `/group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGroupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a group by ID
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a group by ID. If set, 401 may be returned if the user cannot view the group, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (groupId: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('get', 'groupId', groupId)
            const localVarPath = `/group/{groupId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a batch of groups by IDs
         * @param {GetGroupsDto} getGroupsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch: async (getGroupsDto: GetGroupsDto, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getGroupsDto' is not null or undefined
            assertParamExists('getBatch', 'getGroupsDto', getGroupsDto)
            const localVarPath = `/group/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getGroupsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get connections of a group
         * @param {string} groupId 
         * @param {Array<GroupControllerGetConnectionsStateEnum>} [state] Filter connections by state (e.g., requested for pending approvals)
         * @param {Array<GroupControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the group. If set, 401 may be returned if the user cannot view the group connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections: async (groupId: string, state?: Array<GroupControllerGetConnectionsStateEnum>, type?: Array<GroupControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getConnections', 'groupId', groupId)
            const localVarPath = `/group/{groupId}/connections`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (state) {
                localVarQueryParameter['state'] = state;
            }

            if (type) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get events of a group
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of the group. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents: async (groupId: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getEvents', 'groupId', groupId)
            const localVarPath = `/group/{groupId}/events`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (groupId: string, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('remove', 'groupId', groupId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('remove', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/group/{groupId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove a connection from a group
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing a connection from the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeConnection: async (groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('removeConnection', 'groupId', groupId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('removeConnection', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('removeConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'mutateGroupEntityConnectionDto' is not null or undefined
            assertParamExists('removeConnection', 'mutateGroupEntityConnectionDto', mutateGroupEntityConnectionDto)
            const localVarPath = `/group/{groupId}/connection/{userId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mutateGroupEntityConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search groups
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (displayName !== undefined) {
                localVarQueryParameter['displayName'] = displayName;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (minLatitude !== undefined) {
                localVarQueryParameter['minLatitude'] = minLatitude;
            }

            if (maxLatitude !== undefined) {
                localVarQueryParameter['maxLatitude'] = maxLatitude;
            }

            if (minLongitude !== undefined) {
                localVarQueryParameter['minLongitude'] = minLongitude;
            }

            if (maxLongitude !== undefined) {
                localVarQueryParameter['maxLongitude'] = maxLongitude;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the group
         * @param {UpdateGroupDto} updateGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (groupId: string, xProximaNexusRequesterUserId: string, updateGroupDto: UpdateGroupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('update', 'groupId', groupId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('update', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'updateGroupDto' is not null or undefined
            assertParamExists('update', 'updateGroupDto', updateGroupDto)
            const localVarPath = `/group/{groupId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateGroupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupApi - functional programming interface
 */
export const GroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add or update a connection to a group (member, admin, or owner)
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user adding a connection to the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityConnectionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.addConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a group
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the group
         * @param {CreateGroupDto} createGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(xProximaNexusRequesterUserId: string, createGroupDto: CreateGroupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(xProximaNexusRequesterUserId, createGroupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a group by ID
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a group by ID. If set, 401 may be returned if the user cannot view the group, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(groupId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a batch of groups by IDs
         * @param {GetGroupsDto} getGroupsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatch(getGroupsDto: GetGroupsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatch(getGroupsDto, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.getBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get connections of a group
         * @param {string} groupId 
         * @param {Array<GroupControllerGetConnectionsStateEnum>} [state] Filter connections by state (e.g., requested for pending approvals)
         * @param {Array<GroupControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the group. If set, 401 may be returned if the user cannot view the group connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConnections(groupId: string, state?: Array<GroupControllerGetConnectionsStateEnum>, type?: Array<GroupControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConnections(groupId, state, type, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.getConnections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get events of a group
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of the group. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEvents(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEvents(groupId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.getEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(groupId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(groupId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove a connection from a group
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing a connection from the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.removeConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search groups
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the group
         * @param {UpdateGroupDto} updateGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(groupId: string, xProximaNexusRequesterUserId: string, updateGroupDto: UpdateGroupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(groupId, xProximaNexusRequesterUserId, updateGroupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupApi - factory interface
 */
export const GroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupApiFp(configuration)
    return {
        /**
         * 
         * @summary Add or update a connection to a group (member, admin, or owner)
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user adding a connection to the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto> {
            return localVarFp.addConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a group
         * @param {string} xProximaNexusRequesterUserId ID of the user creating the group
         * @param {CreateGroupDto} createGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(xProximaNexusRequesterUserId: string, createGroupDto: CreateGroupDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.create(xProximaNexusRequesterUserId, createGroupDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a group by ID
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a group by ID. If set, 401 may be returned if the user cannot view the group, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<GroupDto> {
            return localVarFp.get(groupId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a batch of groups by IDs
         * @param {GetGroupsDto} getGroupsDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch(getGroupsDto: GetGroupsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupDto>> {
            return localVarFp.getBatch(getGroupsDto, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get connections of a group
         * @param {string} groupId 
         * @param {Array<GroupControllerGetConnectionsStateEnum>} [state] Filter connections by state (e.g., requested for pending approvals)
         * @param {Array<GroupControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the group. If set, 401 may be returned if the user cannot view the group connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections(groupId: string, state?: Array<GroupControllerGetConnectionsStateEnum>, type?: Array<GroupControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>> {
            return localVarFp.getConnections(groupId, state, type, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get events of a group
         * @param {string} groupId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of the group. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>> {
            return localVarFp.getEvents(groupId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(groupId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(groupId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove a connection from a group
         * @param {string} groupId 
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user removing a connection from the group
         * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search groups
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupDto>> {
            return localVarFp.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a group
         * @param {string} groupId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the group
         * @param {UpdateGroupDto} updateGroupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(groupId: string, xProximaNexusRequesterUserId: string, updateGroupDto: UpdateGroupDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.update(groupId, xProximaNexusRequesterUserId, updateGroupDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GroupApi - interface
 */
export interface GroupApiInterface {
    /**
     * 
     * @summary Add or update a connection to a group (member, admin, or owner)
     * @param {string} groupId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user adding a connection to the group
     * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto>;

    /**
     * 
     * @summary Create a group
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the group
     * @param {CreateGroupDto} createGroupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(xProximaNexusRequesterUserId: string, createGroupDto: CreateGroupDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @summary Get a group by ID
     * @param {string} groupId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a group by ID. If set, 401 may be returned if the user cannot view the group, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<GroupDto>;

    /**
     * 
     * @summary Get a batch of groups by IDs
     * @param {GetGroupsDto} getGroupsDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBatch(getGroupsDto: GetGroupsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupDto>>;

    /**
     * 
     * @summary Get connections of a group
     * @param {string} groupId 
     * @param {Array<GroupControllerGetConnectionsStateEnum>} [state] Filter connections by state (e.g., requested for pending approvals)
     * @param {Array<GroupControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the group. If set, 401 may be returned if the user cannot view the group connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConnections(groupId: string, state?: Array<GroupControllerGetConnectionsStateEnum>, type?: Array<GroupControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>>;

    /**
     * 
     * @summary Get events of a group
     * @param {string} groupId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of the group. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEvents(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>>;

    /**
     * 
     * @summary Delete a group
     * @param {string} groupId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(groupId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Remove a connection from a group
     * @param {string} groupId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing a connection from the group
     * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Search groups
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupDto>>;

    /**
     * 
     * @summary Update a group
     * @param {string} groupId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the group
     * @param {UpdateGroupDto} updateGroupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(groupId: string, xProximaNexusRequesterUserId: string, updateGroupDto: UpdateGroupDto, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * GroupApi - object-oriented interface
 */
export class GroupApi extends BaseAPI implements GroupApiInterface {
    /**
     * 
     * @summary Add or update a connection to a group (member, admin, or owner)
     * @param {string} groupId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user adding a connection to the group
     * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).addConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a group
     * @param {string} xProximaNexusRequesterUserId ID of the user creating the group
     * @param {CreateGroupDto} createGroupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(xProximaNexusRequesterUserId: string, createGroupDto: CreateGroupDto, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).create(xProximaNexusRequesterUserId, createGroupDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a group by ID
     * @param {string} groupId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a group by ID. If set, 401 may be returned if the user cannot view the group, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public get(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).get(groupId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a batch of groups by IDs
     * @param {GetGroupsDto} getGroupsDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBatch(getGroupsDto: GetGroupsDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).getBatch(getGroupsDto, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get connections of a group
     * @param {string} groupId 
     * @param {Array<GroupControllerGetConnectionsStateEnum>} [state] Filter connections by state (e.g., requested for pending approvals)
     * @param {Array<GroupControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be a single type or multiple types (comma-separated or array)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting connections of the group. If set, 401 may be returned if the user cannot view the group connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getConnections(groupId: string, state?: Array<GroupControllerGetConnectionsStateEnum>, type?: Array<GroupControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).getConnections(groupId, state, type, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get events of a group
     * @param {string} groupId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of the group. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEvents(groupId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).getEvents(groupId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a group
     * @param {string} groupId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(groupId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).remove(groupId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove a connection from a group
     * @param {string} groupId 
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user removing a connection from the group
     * @param {MutateGroupEntityConnectionDto} mutateGroupEntityConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeConnection(groupId: string, userId: string, xProximaNexusRequesterUserId: string, mutateGroupEntityConnectionDto: MutateGroupEntityConnectionDto, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).removeConnection(groupId, userId, xProximaNexusRequesterUserId, mutateGroupEntityConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search groups
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for groups. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a group
     * @param {string} groupId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the group
     * @param {UpdateGroupDto} updateGroupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(groupId: string, xProximaNexusRequesterUserId: string, updateGroupDto: UpdateGroupDto, options?: RawAxiosRequestConfig) {
        return GroupApiFp(this.configuration).update(groupId, xProximaNexusRequesterUserId, updateGroupDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export enum GroupControllerGetConnectionsStateEnum {
    requested = 'requested',
    active = 'active',
    rejected = 'rejected',
    blocked = 'blocked'
}
export enum GroupControllerGetConnectionsTypeEnum {
    member = 'member',
    admin = 'admin',
    owner = 'owner'
}
