/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateUserDto } from '../models';
// @ts-ignore
import type { EntityConnectionDto } from '../models';
// @ts-ignore
import type { EventEntityConnectionDto } from '../models';
// @ts-ignore
import type { GetUsersDto } from '../models';
// @ts-ignore
import type { GroupEntityConnectionDto } from '../models';
// @ts-ignore
import type { MutateUserResponseDto } from '../models';
// @ts-ignore
import type { UpdateUserDto } from '../models';
// @ts-ignore
import type { UserDto } from '../models';
// @ts-ignore
import type { UserEntityConnectionDto } from '../models';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a friend to a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addFriend: async (userId: string, friendUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addFriend', 'userId', userId)
            // verify required parameter 'friendUserId' is not null or undefined
            assertParamExists('addFriend', 'friendUserId', friendUserId)
            const localVarPath = `/user/{userId}/friends/{friendUserId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"friendUserId"}}`, encodeURIComponent(String(friendUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createUserDto: CreateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUserDto' is not null or undefined
            assertParamExists('create', 'createUserDto', createUserDto)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('findOne', 'userId', userId)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch: async (getUsersDto: GetUsersDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getUsersDto' is not null or undefined
            assertParamExists('getBatch', 'getUsersDto', getUsersDto)
            const localVarPath = `/user/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getUsersDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getEvents', 'userId', userId)
            const localVarPath = `/user/{userId}/events`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get friends of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriends: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getFriends', 'userId', userId)
            const localVarPath = `/user/{userId}/friends`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroups: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getGroups', 'userId', userId)
            const localVarPath = `/user/{userId}/groups`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('remove', 'userId', userId)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove a friend from a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFriend: async (userId: string, friendUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('removeFriend', 'userId', userId)
            // verify required parameter 'friendUserId' is not null or undefined
            assertParamExists('removeFriend', 'friendUserId', friendUserId)
            const localVarPath = `/user/{userId}/friends/{friendUserId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"friendUserId"}}`, encodeURIComponent(String(friendUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (displayName !== undefined) {
                localVarQueryParameter['displayName'] = displayName;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (minLatitude !== undefined) {
                localVarQueryParameter['minLatitude'] = minLatitude;
            }

            if (maxLatitude !== undefined) {
                localVarQueryParameter['maxLatitude'] = maxLatitude;
            }

            if (minLongitude !== undefined) {
                localVarQueryParameter['minLongitude'] = minLongitude;
            }

            if (maxLongitude !== undefined) {
                localVarQueryParameter['maxLongitude'] = maxLongitude;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (userId: string, updateUserDto: UpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('update', 'userId', userId)
            // verify required parameter 'updateUserDto' is not null or undefined
            assertParamExists('update', 'updateUserDto', updateUserDto)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a friend to a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityConnectionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addFriend(userId, friendUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.addFriend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MutateUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findOne(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findOne(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.findOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatch(getUsersDto: GetUsersDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatch(getUsersDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEvents(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEvents(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get friends of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFriends(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFriends(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getFriends']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroups(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroups(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove a friend from a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeFriend(userId, friendUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.removeFriend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(userId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MutateUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(userId, updateUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a friend to a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto> {
            return localVarFp.addFriend(userId, friendUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto> {
            return localVarFp.create(createUserDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findOne(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserDto> {
            return localVarFp.findOne(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch(getUsersDto: GetUsersDto, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>> {
            return localVarFp.getBatch(getUsersDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>> {
            return localVarFp.getEvents(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get friends of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriends(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>> {
            return localVarFp.getFriends(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroups(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupEntityConnectionDto>> {
            return localVarFp.getGroups(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove a friend from a user
         * @param {string} userId 
         * @param {string} friendUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeFriend(userId, friendUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>> {
            return localVarFp.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(userId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto> {
            return localVarFp.update(userId, updateUserDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - interface
 */
export interface UserApiInterface {
    /**
     * 
     * @summary Add a friend to a user
     * @param {string} userId 
     * @param {string} friendUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto>;

    /**
     * 
     * @summary Create a user
     * @param {CreateUserDto} createUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto>;

    /**
     * 
     * @summary Get a user by ID
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findOne(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserDto>;

    /**
     * 
     * @summary Get a batch of users by IDs
     * @param {GetUsersDto} getUsersDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBatch(getUsersDto: GetUsersDto, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>>;

    /**
     * 
     * @summary Get events of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEvents(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>>;

    /**
     * 
     * @summary Get friends of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFriends(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>>;

    /**
     * 
     * @summary Get groups of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getGroups(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupEntityConnectionDto>>;

    /**
     * 
     * @summary Delete a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Remove a friend from a user
     * @param {string} userId 
     * @param {string} friendUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Search users
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>>;

    /**
     * 
     * @summary Update a user
     * @param {string} userId 
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(userId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto>;

}

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI implements UserApiInterface {
    /**
     * 
     * @summary Add a friend to a user
     * @param {string} userId 
     * @param {string} friendUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).addFriend(userId, friendUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a user
     * @param {CreateUserDto} createUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).create(createUserDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a user by ID
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public findOne(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).findOne(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a batch of users by IDs
     * @param {GetUsersDto} getUsersDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBatch(getUsersDto: GetUsersDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getBatch(getUsersDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get events of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEvents(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getEvents(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get friends of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFriends(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getFriends(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get groups of a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGroups(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getGroups(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).remove(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove a friend from a user
     * @param {string} userId 
     * @param {string} friendUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeFriend(userId: string, friendUserId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).removeFriend(userId, friendUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search users
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user
     * @param {string} userId 
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(userId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).update(userId, updateUserDto, options).then((request) => request(this.axios, this.basePath));
    }
}

