/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateUserDto } from '../models';
// @ts-ignore
import type { EntityConnectionDto } from '../models';
// @ts-ignore
import type { EventEntityConnectionDto } from '../models';
// @ts-ignore
import type { GetUsersDto } from '../models';
// @ts-ignore
import type { GroupEntityConnectionDto } from '../models';
// @ts-ignore
import type { MutateUserConnectionDto } from '../models';
// @ts-ignore
import type { MutateUserResponseDto } from '../models';
// @ts-ignore
import type { UpdateUserDto } from '../models';
// @ts-ignore
import type { UserDto } from '../models';
// @ts-ignore
import type { UserEntityConnectionDto } from '../models';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createUserDto: CreateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUserDto' is not null or undefined
            assertParamExists('create', 'createUserDto', createUserDto)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a friend connection or unblock a user. For BLOCKED connections, only the user who initiated the block can unblock.
         * @summary Delete a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {UserControllerDeleteConnectionTypeEnum} type Type of connection to delete
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteConnection: async (userId: string, targetUserId: string, type: UserControllerDeleteConnectionTypeEnum, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteConnection', 'userId', userId)
            // verify required parameter 'targetUserId' is not null or undefined
            assertParamExists('deleteConnection', 'targetUserId', targetUserId)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('deleteConnection', 'type', type)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('deleteConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/user/{userId}/connections/{targetUserId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"targetUserId"}}`, encodeURIComponent(String(targetUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a user by ID. If set, 401 may be returned if the user cannot view the user, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (userId: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('get', 'userId', userId)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch: async (getUsersDto: GetUsersDto, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getUsersDto' is not null or undefined
            assertParamExists('getBatch', 'getUsersDto', getUsersDto)
            const localVarPath = `/user/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getUsersDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user connections with optional type and state filters. Visibility rules apply: HIDDEN/CONNECTIONS users only show connections to self or connected users. Only the user themselves can see BLOCKED connections or non-ACTIVE states.
         * @summary Get connections of a user
         * @param {string} userId 
         * @param {Array<UserControllerGetConnectionsStateEnum>} [state] Filter connections by state. Can be multiple values. Non-self requesters can only see ACTIVE connections.
         * @param {Array<UserControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be multiple values.
         * @param {string} [xProximaNexusRequesterUserId] ID of the user viewing connections. Required for non-PUBLIC users. Only the user themselves can view BLOCKED or non-ACTIVE connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections: async (userId: string, state?: Array<UserControllerGetConnectionsStateEnum>, type?: Array<UserControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getConnections', 'userId', userId)
            const localVarPath = `/user/{userId}/connections`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (state) {
                localVarQueryParameter['state'] = state;
            }

            if (type) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {string} [from] ISO 8601 start of range (events ending after this time). Default: NOW()
         * @param {string} [to] ISO 8601 end of range (events starting before this time)
         * @param {string} [latitude] Requester latitude for nearby event discovery
         * @param {string} [longitude] Requester longitude for nearby event discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of a user. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents: async (userId: string, from?: string, to?: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getEvents', 'userId', userId)
            const localVarPath = `/user/{userId}/events`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {string} [latitude] Requester latitude for nearby group discovery
         * @param {string} [longitude] Requester longitude for nearby group discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting groups of a user. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroups: async (userId: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getGroups', 'userId', userId)
            const localVarPath = `/user/{userId}/groups`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a friend request, accept a pending request, or block a user. For FRIEND type: creates REQUESTED state if no connection exists; target user can accept by setting state to ACTIVE. For BLOCKED type: creates a mutual block.
         * @summary Create or update a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {string} xProximaNexusRequesterUserId ID of the user creating/modifying the connection (must match userId)
         * @param {MutateUserConnectionDto} mutateUserConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putConnection: async (userId: string, targetUserId: string, xProximaNexusRequesterUserId: string, mutateUserConnectionDto: MutateUserConnectionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('putConnection', 'userId', userId)
            // verify required parameter 'targetUserId' is not null or undefined
            assertParamExists('putConnection', 'targetUserId', targetUserId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('putConnection', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'mutateUserConnectionDto' is not null or undefined
            assertParamExists('putConnection', 'mutateUserConnectionDto', mutateUserConnectionDto)
            const localVarPath = `/user/{userId}/connections/{targetUserId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"targetUserId"}}`, encodeURIComponent(String(targetUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mutateUserConnectionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove: async (userId: string, xProximaNexusRequesterUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('remove', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('remove', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)


            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for users. When requesterUserId is provided, HIDDEN users are filtered out unless the requester is connected to them, and users who have blocked the requester are also filtered out. When requesterUserId is not provided, all users are returned without visibility filtering.
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [from] ISO 8601 date — filter events ending after this time
         * @param {string} [to] ISO 8601 date — filter events starting before this time
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, from?: string, to?: string, xProximaNexusRequesterUserId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            if (displayName !== undefined) {
                localVarQueryParameter['displayName'] = displayName;
            }

            if (latitude !== undefined) {
                localVarQueryParameter['latitude'] = latitude;
            }

            if (longitude !== undefined) {
                localVarQueryParameter['longitude'] = longitude;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }

            if (minLatitude !== undefined) {
                localVarQueryParameter['minLatitude'] = minLatitude;
            }

            if (maxLatitude !== undefined) {
                localVarQueryParameter['maxLatitude'] = maxLatitude;
            }

            if (minLongitude !== undefined) {
                localVarQueryParameter['minLongitude'] = minLongitude;
            }

            if (maxLongitude !== undefined) {
                localVarQueryParameter['maxLongitude'] = maxLongitude;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the user
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (userId: string, xProximaNexusRequesterUserId: string, updateUserDto: UpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('update', 'userId', userId)
            // verify required parameter 'xProximaNexusRequesterUserId' is not null or undefined
            assertParamExists('update', 'xProximaNexusRequesterUserId', xProximaNexusRequesterUserId)
            // verify required parameter 'updateUserDto' is not null or undefined
            assertParamExists('update', 'updateUserDto', updateUserDto)
            const localVarPath = `/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-Proxima-Nexus-Api-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xProximaNexusRequesterUserId != null) {
                localVarHeaderParameter['X-Proxima-Nexus-Requester-User-Id'] = String(xProximaNexusRequesterUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MutateUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove a friend connection or unblock a user. For BLOCKED connections, only the user who initiated the block can unblock.
         * @summary Delete a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {UserControllerDeleteConnectionTypeEnum} type Type of connection to delete
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteConnection(userId: string, targetUserId: string, type: UserControllerDeleteConnectionTypeEnum, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteConnection(userId, targetUserId, type, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.deleteConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a user by ID. If set, 401 may be returned if the user cannot view the user, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(userId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(userId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatch(getUsersDto: GetUsersDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatch(getUsersDto, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get user connections with optional type and state filters. Visibility rules apply: HIDDEN/CONNECTIONS users only show connections to self or connected users. Only the user themselves can see BLOCKED connections or non-ACTIVE states.
         * @summary Get connections of a user
         * @param {string} userId 
         * @param {Array<UserControllerGetConnectionsStateEnum>} [state] Filter connections by state. Can be multiple values. Non-self requesters can only see ACTIVE connections.
         * @param {Array<UserControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be multiple values.
         * @param {string} [xProximaNexusRequesterUserId] ID of the user viewing connections. Required for non-PUBLIC users. Only the user themselves can view BLOCKED or non-ACTIVE connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConnections(userId: string, state?: Array<UserControllerGetConnectionsStateEnum>, type?: Array<UserControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConnections(userId, state, type, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getConnections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {string} [from] ISO 8601 start of range (events ending after this time). Default: NOW()
         * @param {string} [to] ISO 8601 end of range (events starting before this time)
         * @param {string} [latitude] Requester latitude for nearby event discovery
         * @param {string} [longitude] Requester longitude for nearby event discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of a user. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEvents(userId: string, from?: string, to?: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEvents(userId, from, to, latitude, longitude, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {string} [latitude] Requester latitude for nearby group discovery
         * @param {string} [longitude] Requester longitude for nearby group discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting groups of a user. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroups(userId: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupEntityConnectionDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroups(userId, latitude, longitude, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a friend request, accept a pending request, or block a user. For FRIEND type: creates REQUESTED state if no connection exists; target user can accept by setting state to ACTIVE. For BLOCKED type: creates a mutual block.
         * @summary Create or update a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {string} xProximaNexusRequesterUserId ID of the user creating/modifying the connection (must match userId)
         * @param {MutateUserConnectionDto} mutateUserConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putConnection(userId: string, targetUserId: string, xProximaNexusRequesterUserId: string, mutateUserConnectionDto: MutateUserConnectionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityConnectionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putConnection(userId, targetUserId, xProximaNexusRequesterUserId, mutateUserConnectionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.putConnection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove(userId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remove(userId, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.remove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search for users. When requesterUserId is provided, HIDDEN users are filtered out unless the requester is connected to them, and users who have blocked the requester are also filtered out. When requesterUserId is not provided, all users are returned without visibility filtering.
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [from] ISO 8601 date — filter events ending after this time
         * @param {string} [to] ISO 8601 date — filter events starting before this time
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, from?: string, to?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, from, to, xProximaNexusRequesterUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the user
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(userId: string, xProximaNexusRequesterUserId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MutateUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(userId, xProximaNexusRequesterUserId, updateUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a user
         * @param {CreateUserDto} createUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto> {
            return localVarFp.create(createUserDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a friend connection or unblock a user. For BLOCKED connections, only the user who initiated the block can unblock.
         * @summary Delete a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {UserControllerDeleteConnectionTypeEnum} type Type of connection to delete
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteConnection(userId: string, targetUserId: string, type: UserControllerDeleteConnectionTypeEnum, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteConnection(userId, targetUserId, type, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} userId 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a user by ID. If set, 401 may be returned if the user cannot view the user, otherwise requesterConnection will be set on the result.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(userId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<UserDto> {
            return localVarFp.get(userId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a batch of users by IDs
         * @param {GetUsersDto} getUsersDto 
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatch(getUsersDto: GetUsersDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>> {
            return localVarFp.getBatch(getUsersDto, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user connections with optional type and state filters. Visibility rules apply: HIDDEN/CONNECTIONS users only show connections to self or connected users. Only the user themselves can see BLOCKED connections or non-ACTIVE states.
         * @summary Get connections of a user
         * @param {string} userId 
         * @param {Array<UserControllerGetConnectionsStateEnum>} [state] Filter connections by state. Can be multiple values. Non-self requesters can only see ACTIVE connections.
         * @param {Array<UserControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be multiple values.
         * @param {string} [xProximaNexusRequesterUserId] ID of the user viewing connections. Required for non-PUBLIC users. Only the user themselves can view BLOCKED or non-ACTIVE connections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConnections(userId: string, state?: Array<UserControllerGetConnectionsStateEnum>, type?: Array<UserControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>> {
            return localVarFp.getConnections(userId, state, type, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get events of a user
         * @param {string} userId 
         * @param {string} [from] ISO 8601 start of range (events ending after this time). Default: NOW()
         * @param {string} [to] ISO 8601 end of range (events starting before this time)
         * @param {string} [latitude] Requester latitude for nearby event discovery
         * @param {string} [longitude] Requester longitude for nearby event discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of a user. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEvents(userId: string, from?: string, to?: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>> {
            return localVarFp.getEvents(userId, from, to, latitude, longitude, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get groups of a user
         * @param {string} userId 
         * @param {string} [latitude] Requester latitude for nearby group discovery
         * @param {string} [longitude] Requester longitude for nearby group discovery
         * @param {string} [xProximaNexusRequesterUserId] ID of the user getting groups of a user. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroups(userId: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupEntityConnectionDto>> {
            return localVarFp.getGroups(userId, latitude, longitude, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a friend request, accept a pending request, or block a user. For FRIEND type: creates REQUESTED state if no connection exists; target user can accept by setting state to ACTIVE. For BLOCKED type: creates a mutual block.
         * @summary Create or update a connection with another user
         * @param {string} userId 
         * @param {string} targetUserId 
         * @param {string} xProximaNexusRequesterUserId ID of the user creating/modifying the connection (must match userId)
         * @param {MutateUserConnectionDto} mutateUserConnectionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putConnection(userId: string, targetUserId: string, xProximaNexusRequesterUserId: string, mutateUserConnectionDto: MutateUserConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto> {
            return localVarFp.putConnection(userId, targetUserId, xProximaNexusRequesterUserId, mutateUserConnectionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user deleting the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove(userId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remove(userId, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * Search for users. When requesterUserId is provided, HIDDEN users are filtered out unless the requester is connected to them, and users who have blocked the requester are also filtered out. When requesterUserId is not provided, all users are returned without visibility filtering.
         * @summary Search users
         * @param {string} [displayName] Display name search (ILIKE)
         * @param {number} [latitude] Latitude for radius search
         * @param {number} [longitude] Longitude for radius search
         * @param {number} [radius] Radius in meters for radius search
         * @param {number} [minLatitude] Minimum latitude for bounding box
         * @param {number} [maxLatitude] Maximum latitude for bounding box
         * @param {number} [minLongitude] Minimum longitude for bounding box
         * @param {number} [maxLongitude] Maximum longitude for bounding box
         * @param {number} [limit] Limit results (1-1000)
         * @param {string} [from] ISO 8601 date — filter events ending after this time
         * @param {string} [to] ISO 8601 date — filter events starting before this time
         * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, from?: string, to?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>> {
            return localVarFp.search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, from, to, xProximaNexusRequesterUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user
         * @param {string} userId 
         * @param {string} xProximaNexusRequesterUserId ID of the user updating the user
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(userId: string, xProximaNexusRequesterUserId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto> {
            return localVarFp.update(userId, xProximaNexusRequesterUserId, updateUserDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - interface
 */
export interface UserApiInterface {
    /**
     * 
     * @summary Create a user
     * @param {CreateUserDto} createUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto>;

    /**
     * Remove a friend connection or unblock a user. For BLOCKED connections, only the user who initiated the block can unblock.
     * @summary Delete a connection with another user
     * @param {string} userId 
     * @param {string} targetUserId 
     * @param {UserControllerDeleteConnectionTypeEnum} type Type of connection to delete
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the connection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteConnection(userId: string, targetUserId: string, type: UserControllerDeleteConnectionTypeEnum, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a user by ID
     * @param {string} userId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a user by ID. If set, 401 may be returned if the user cannot view the user, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(userId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<UserDto>;

    /**
     * 
     * @summary Get a batch of users by IDs
     * @param {GetUsersDto} getUsersDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBatch(getUsersDto: GetUsersDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>>;

    /**
     * Get user connections with optional type and state filters. Visibility rules apply: HIDDEN/CONNECTIONS users only show connections to self or connected users. Only the user themselves can see BLOCKED connections or non-ACTIVE states.
     * @summary Get connections of a user
     * @param {string} userId 
     * @param {Array<UserControllerGetConnectionsStateEnum>} [state] Filter connections by state. Can be multiple values. Non-self requesters can only see ACTIVE connections.
     * @param {Array<UserControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be multiple values.
     * @param {string} [xProximaNexusRequesterUserId] ID of the user viewing connections. Required for non-PUBLIC users. Only the user themselves can view BLOCKED or non-ACTIVE connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConnections(userId: string, state?: Array<UserControllerGetConnectionsStateEnum>, type?: Array<UserControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEntityConnectionDto>>;

    /**
     * 
     * @summary Get events of a user
     * @param {string} userId 
     * @param {string} [from] ISO 8601 start of range (events ending after this time). Default: NOW()
     * @param {string} [to] ISO 8601 end of range (events starting before this time)
     * @param {string} [latitude] Requester latitude for nearby event discovery
     * @param {string} [longitude] Requester longitude for nearby event discovery
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of a user. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEvents(userId: string, from?: string, to?: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<EventEntityConnectionDto>>;

    /**
     * 
     * @summary Get groups of a user
     * @param {string} userId 
     * @param {string} [latitude] Requester latitude for nearby group discovery
     * @param {string} [longitude] Requester longitude for nearby group discovery
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting groups of a user. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getGroups(userId: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupEntityConnectionDto>>;

    /**
     * Create a friend request, accept a pending request, or block a user. For FRIEND type: creates REQUESTED state if no connection exists; target user can accept by setting state to ACTIVE. For BLOCKED type: creates a mutual block.
     * @summary Create or update a connection with another user
     * @param {string} userId 
     * @param {string} targetUserId 
     * @param {string} xProximaNexusRequesterUserId ID of the user creating/modifying the connection (must match userId)
     * @param {MutateUserConnectionDto} mutateUserConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    putConnection(userId: string, targetUserId: string, xProximaNexusRequesterUserId: string, mutateUserConnectionDto: MutateUserConnectionDto, options?: RawAxiosRequestConfig): AxiosPromise<EntityConnectionDto>;

    /**
     * 
     * @summary Delete a user
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    remove(userId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Search for users. When requesterUserId is provided, HIDDEN users are filtered out unless the requester is connected to them, and users who have blocked the requester are also filtered out. When requesterUserId is not provided, all users are returned without visibility filtering.
     * @summary Search users
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [from] ISO 8601 date — filter events ending after this time
     * @param {string} [to] ISO 8601 date — filter events starting before this time
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, from?: string, to?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserDto>>;

    /**
     * 
     * @summary Update a user
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the user
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    update(userId: string, xProximaNexusRequesterUserId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<MutateUserResponseDto>;

}

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI implements UserApiInterface {
    /**
     * 
     * @summary Create a user
     * @param {CreateUserDto} createUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(createUserDto: CreateUserDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).create(createUserDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove a friend connection or unblock a user. For BLOCKED connections, only the user who initiated the block can unblock.
     * @summary Delete a connection with another user
     * @param {string} userId 
     * @param {string} targetUserId 
     * @param {UserControllerDeleteConnectionTypeEnum} type Type of connection to delete
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the connection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteConnection(userId: string, targetUserId: string, type: UserControllerDeleteConnectionTypeEnum, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).deleteConnection(userId, targetUserId, type, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a user by ID
     * @param {string} userId 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a user by ID. If set, 401 may be returned if the user cannot view the user, otherwise requesterConnection will be set on the result.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public get(userId: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).get(userId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a batch of users by IDs
     * @param {GetUsersDto} getUsersDto 
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting a batch of users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBatch(getUsersDto: GetUsersDto, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getBatch(getUsersDto, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get user connections with optional type and state filters. Visibility rules apply: HIDDEN/CONNECTIONS users only show connections to self or connected users. Only the user themselves can see BLOCKED connections or non-ACTIVE states.
     * @summary Get connections of a user
     * @param {string} userId 
     * @param {Array<UserControllerGetConnectionsStateEnum>} [state] Filter connections by state. Can be multiple values. Non-self requesters can only see ACTIVE connections.
     * @param {Array<UserControllerGetConnectionsTypeEnum>} [type] Filter connections by type. Can be multiple values.
     * @param {string} [xProximaNexusRequesterUserId] ID of the user viewing connections. Required for non-PUBLIC users. Only the user themselves can view BLOCKED or non-ACTIVE connections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getConnections(userId: string, state?: Array<UserControllerGetConnectionsStateEnum>, type?: Array<UserControllerGetConnectionsTypeEnum>, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getConnections(userId, state, type, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get events of a user
     * @param {string} userId 
     * @param {string} [from] ISO 8601 start of range (events ending after this time). Default: NOW()
     * @param {string} [to] ISO 8601 end of range (events starting before this time)
     * @param {string} [latitude] Requester latitude for nearby event discovery
     * @param {string} [longitude] Requester longitude for nearby event discovery
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting events of a user. If set, events will be filtered to only include events that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEvents(userId: string, from?: string, to?: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getEvents(userId, from, to, latitude, longitude, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get groups of a user
     * @param {string} userId 
     * @param {string} [latitude] Requester latitude for nearby group discovery
     * @param {string} [longitude] Requester longitude for nearby group discovery
     * @param {string} [xProximaNexusRequesterUserId] ID of the user getting groups of a user. If set, groups will be filtered to only include groups that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGroups(userId: string, latitude?: string, longitude?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getGroups(userId, latitude, longitude, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a friend request, accept a pending request, or block a user. For FRIEND type: creates REQUESTED state if no connection exists; target user can accept by setting state to ACTIVE. For BLOCKED type: creates a mutual block.
     * @summary Create or update a connection with another user
     * @param {string} userId 
     * @param {string} targetUserId 
     * @param {string} xProximaNexusRequesterUserId ID of the user creating/modifying the connection (must match userId)
     * @param {MutateUserConnectionDto} mutateUserConnectionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public putConnection(userId: string, targetUserId: string, xProximaNexusRequesterUserId: string, mutateUserConnectionDto: MutateUserConnectionDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).putConnection(userId, targetUserId, xProximaNexusRequesterUserId, mutateUserConnectionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user deleting the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public remove(userId: string, xProximaNexusRequesterUserId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).remove(userId, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search for users. When requesterUserId is provided, HIDDEN users are filtered out unless the requester is connected to them, and users who have blocked the requester are also filtered out. When requesterUserId is not provided, all users are returned without visibility filtering.
     * @summary Search users
     * @param {string} [displayName] Display name search (ILIKE)
     * @param {number} [latitude] Latitude for radius search
     * @param {number} [longitude] Longitude for radius search
     * @param {number} [radius] Radius in meters for radius search
     * @param {number} [minLatitude] Minimum latitude for bounding box
     * @param {number} [maxLatitude] Maximum latitude for bounding box
     * @param {number} [minLongitude] Minimum longitude for bounding box
     * @param {number} [maxLongitude] Maximum longitude for bounding box
     * @param {number} [limit] Limit results (1-1000)
     * @param {string} [from] ISO 8601 date — filter events ending after this time
     * @param {string} [to] ISO 8601 date — filter events starting before this time
     * @param {string} [xProximaNexusRequesterUserId] ID of the user searching for users. If set, users will be filtered to only include users that the user can see, and requesterConnection will be set on the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(displayName?: string, latitude?: number, longitude?: number, radius?: number, minLatitude?: number, maxLatitude?: number, minLongitude?: number, maxLongitude?: number, limit?: number, from?: string, to?: string, xProximaNexusRequesterUserId?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).search(displayName, latitude, longitude, radius, minLatitude, maxLatitude, minLongitude, maxLongitude, limit, from, to, xProximaNexusRequesterUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user
     * @param {string} userId 
     * @param {string} xProximaNexusRequesterUserId ID of the user updating the user
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(userId: string, xProximaNexusRequesterUserId: string, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).update(userId, xProximaNexusRequesterUserId, updateUserDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export enum UserControllerDeleteConnectionTypeEnum {
    friend = 'friend',
    blocked = 'blocked'
}
export enum UserControllerGetConnectionsStateEnum {
    incoming_request = 'incoming_request',
    outgoing_request = 'outgoing_request',
    active = 'active'
}
export enum UserControllerGetConnectionsTypeEnum {
    friend = 'friend',
    blocked = 'blocked'
}
