/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface CreateGroupDto {
    /**
     * Display name
     */
    'displayName': string;
    /**
     * Visibility of the entity
     */
    'visibility': CreateGroupDtoVisibilityEnum;
    /**
     * Optional location information
     */
    'location'?: LocationDto;
    /**
     * Entity description
     */
    'description'?: string;
    /**
     * Entity tags
     */
    'tags'?: Array<string>;
    /**
     * Unique group identifier
     */
    'groupId': string;
    /**
     * Group type
     */
    'type': CreateGroupDtoTypeEnum;
}

export enum CreateGroupDtoVisibilityEnum {
    public = 'public',
    connections = 'connections',
    hidden = 'hidden'
}
export enum CreateGroupDtoTypeEnum {
    open = 'open',
    request = 'request',
    invite = 'invite'
}


