/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface CreateEventSeriesDto {
    /**
     * Display name
     */
    'displayName': string;
    /**
     * Visibility of the entity
     */
    'visibility': CreateEventSeriesDtoVisibilityEnum;
    /**
     * Optional location information
     */
    'location'?: LocationDto;
    /**
     * Entity description
     */
    'description'?: string;
    /**
     * Entity tags
     */
    'tags'?: Array<string>;
    /**
     * Unique series identifier
     */
    'seriesId': string;
    /**
     * Event type
     */
    'type': string;
    /**
     * iCal RRULE string (without DTSTART). Defines the recurrence pattern.
     */
    'rrule': string;
    /**
     * Date of the first occurrence in YYYY-MM-DD format (local date in the given timezone)
     */
    'startDate': string;
    /**
     * Start time of each instance in HH:MM format (local time in the given timezone)
     */
    'instanceStartTime': string;
    /**
     * End time of each instance in HH:MM format (local time in the given timezone)
     */
    'instanceEndTime': string;
    /**
     * IANA timezone for interpreting times and generating instances
     */
    'timezone': string;
    /**
     * Identifier of the associated group. Owners/admins of the group will be admins of the series.
     */
    'associatedGroupId'?: string;
    /**
     * Maximum number of attendees per event instance (null = unlimited)
     */
    'maxNumAttendees'?: number;
}

export enum CreateEventSeriesDtoVisibilityEnum {
    public = 'public',
    connections = 'connections',
    hidden = 'hidden'
}


