/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EntityConnectionDto {
    /**
     * Date/time the connection was created (ISO string)
     */
    'createdAt'?: string;
    /**
     * Date/time the connection was last updated (ISO string)
     */
    'updatedAt'?: string;
    /**
     * Connection state
     */
    'state': EntityConnectionDtoStateEnum;
}

export enum EntityConnectionDtoStateEnum {
    requested = 'requested',
    active = 'active',
    rejected = 'rejected'
}


