/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityConnectionDto } from './entity-connection-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface EventDto {
    /**
     * Unique identifier for the entity
     */
    'entityId'?: string;
    /**
     * Display name of the entity
     */
    'displayName'?: string;
    /**
     * Visibility of the entity
     */
    'visibility'?: EventDtoVisibilityEnum;
    /**
     * Description of the entity
     */
    'description'?: string;
    /**
     * Tags associated with the entity
     */
    'tags'?: Array<string>;
    /**
     * Date/time the entity was created (ISO string)
     */
    'createdAt'?: string;
    /**
     * Date/time the entity was last updated (ISO string)
     */
    'updatedAt'?: string;
    /**
     * Required location information
     */
    'location'?: LocationDto;
    /**
     * Connection to the requester
     */
    'requesterConnection'?: EntityConnectionDto;
    /**
     * Start time (ISO 8601)
     */
    'startTime': string;
    /**
     * End time (ISO 8601)
     */
    'endTime': string;
    /**
     * Event type
     */
    'type': string;
    /**
     * Identifier of associated group which owns the event. Owners/admins of the group will be admins of the event.
     */
    'associatedGroupId'?: string;
    /**
     * Number of active attendees
     */
    'numAttendees'?: number;
    /**
     * Maximum number of attendees allowed (null = unlimited)
     */
    'maxNumAttendees'?: number;
}

export enum EventDtoVisibilityEnum {
    PUBLIC = 'PUBLIC',
    PRIVATE = 'PRIVATE'
}


