/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EventEntityConnectionDto {
    /**
     * Date/time the connection was created (ISO string)
     */
    'createdAt'?: string;
    /**
     * Date/time the connection was last updated (ISO string)
     */
    'updatedAt'?: string;
    /**
     * Connection state
     */
    'state': EventEntityConnectionDtoStateEnum;
    /**
     * Connection type
     */
    'type': EventEntityConnectionDtoTypeEnum;
    /**
     * Event ID
     */
    'eventId': string;
}

export enum EventEntityConnectionDtoStateEnum {
    requested = 'requested',
    active = 'active',
    rejected = 'rejected',
    blocked = 'blocked'
}
export enum EventEntityConnectionDtoTypeEnum {
    attendee = 'attendee',
    admin = 'admin',
    owner = 'owner',
    member = 'member',
    admin2 = 'admin',
    owner2 = 'owner',
    friend = 'friend',
    blocked = 'blocked',
    none = 'none'
}


