/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LocationDto {
    /**
     * Latitude in decimal degrees
     */
    'latitude'?: number;
    /**
     * Longitude in decimal degrees
     */
    'longitude'?: number;
    /**
     * Human-readable location name
     */
    'name'?: string;
}

