/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MutateEventEntityConnectionDto {
    /**
     * Connection type
     */
    'type': MutateEventEntityConnectionDtoTypeEnum;
}

export enum MutateEventEntityConnectionDtoTypeEnum {
    attendee = 'attendee',
    admin = 'admin',
    owner = 'owner',
    associated_group = 'associated_group',
    nearby = 'nearby'
}


