/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface UpdateEventSeriesDto {
    /**
     * Visibility of the entity
     */
    'visibility'?: UpdateEventSeriesDtoVisibilityEnum;
    /**
     * Display name
     */
    'displayName'?: string;
    /**
     * Optional location information
     */
    'location'?: LocationDto;
    /**
     * Entity description
     */
    'description'?: string;
    /**
     * Entity tags
     */
    'tags'?: Array<string>;
    /**
     * Event type
     */
    'type'?: string;
    /**
     * Maximum number of attendees per event instance (null = unlimited)
     */
    'maxNumAttendees'?: number;
    /**
     * Registration fee amount in minor units (e.g. cents). Set to null to remove the fee.
     */
    'registrationFeeAmount'?: object;
    /**
     * ISO 4217 currency code, lowercase (e.g. eur). Set to null to remove the fee.
     */
    'registrationFeeCurrency'?: object;
    /**
     * Start time of each instance in HH:MM format (local time in the given timezone). Changing this regenerates upcoming instances.
     */
    'instanceStartTime'?: string;
    /**
     * End time of each instance in HH:MM format (local time in the given timezone). Changing this regenerates upcoming instances.
     */
    'instanceEndTime'?: string;
    /**
     * IANA timezone for interpreting times and generating instances. Changing this regenerates upcoming instances.
     */
    'timezone'?: string;
    /**
     * New end date for the series (YYYY-MM-DD). May only be moved later; extending appends new upcoming instances up to the new end without disturbing existing ones. Moving it earlier is rejected.
     */
    'seriesEndDate'?: string;
}

export enum UpdateEventSeriesDtoVisibilityEnum {
    public = 'public',
    connections = 'connections',
    hidden = 'hidden'
}


