/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface UpdateEventDto {
    /**
     * Visibility of the entity
     */
    'visibility'?: UpdateEventDtoVisibilityEnum;
    /**
     * Display name
     */
    'displayName': string;
    /**
     * Optional location information
     */
    'location'?: LocationDto;
    /**
     * Entity description
     */
    'description'?: string;
    /**
     * Entity tags
     */
    'tags'?: Array<string>;
    /**
     * Start time (ISO 8601)
     */
    'startTime': string;
    /**
     * End time (ISO 8601)
     */
    'endTime': string;
    /**
     * Event type
     */
    'type': string;
    /**
     * Maximum number of attendees allowed (null = unlimited)
     */
    'maxNumAttendees'?: number;
}

export enum UpdateEventDtoVisibilityEnum {
    public = 'public',
    connections = 'connections',
    hidden = 'hidden'
}


