/* tslint:disable */
/* eslint-disable */
/**
 * proxima-nexus-data-plane-api
 * Proxima Nexus Data Plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityConnectionDto } from './entity-connection-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

export interface UserDto {
    /**
     * Unique identifier for the entity
     */
    'entityId'?: string;
    /**
     * Display name of the entity
     */
    'displayName'?: string;
    /**
     * Visibility of the entity
     */
    'visibility'?: UserDtoVisibilityEnum;
    /**
     * Description of the entity
     */
    'description'?: string;
    /**
     * Tags associated with the entity
     */
    'tags'?: Array<string>;
    /**
     * Date/time the entity was created (ISO string)
     */
    'createdAt'?: string;
    /**
     * Date/time the entity was last updated (ISO string)
     */
    'updatedAt'?: string;
    /**
     * Required location information
     */
    'location'?: LocationDto;
    /**
     * Connection to the requester
     */
    'requesterConnection'?: EntityConnectionDto;
    /**
     * Gender
     */
    'gender': string;
    /**
     * Birth date (ISO 8601)
     */
    'birthDate': string;
}

export enum UserDtoVisibilityEnum {
    PUBLIC = 'PUBLIC',
    PRIVATE = 'PRIVATE'
}


